server:
  port: 8888
zookeeper:
  address: 172.25.51.88:2181
dubbo:
  application:
    name: gateway
  protocol:
    name: dubbo
    port: -1
    serialization: jackson
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1:2181}
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nuturbo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver