server:
  port: 8888
zookeeper:
  address: 172.25.51.88:2181
dubbo:
  application:
    name: gateway
  protocol:
    name: dubbo
    port: -1
    serialization: jackson
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1:2181}
  consumer:
    check: false

jwt:
  expireTime: 1800 # 单位分钟