server:
  port: 8081
zookeeper:
  address: 172.25.51.88:2181
dubbo:
  application:
    name: card-server
  protocol:
    name: dubbo
    port: -1
    serialization: jackson
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1:2181}
  consumer:
    check: false
  provider:
    filter: customExceptionFilter